# Generated by Django 4.0.6 on 2022-07-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_comedy_movie_drama_movie_horror_movie_romanse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='anime',
            field=models.BooleanField(default=False, verbose_name='Жанр - аниме'),
        ),
        migrations.AddField(
            model_name='movie',
            name='films_comedy',
            field=models.BooleanField(default=False, verbose_name='Жанр - комедия'),
        ),
        migrations.AddField(
            model_name='movie',
            name='films_drama',
            field=models.BooleanField(default=False, verbose_name='Жанр - мелодрама'),
        ),
        migrations.AddField(
            model_name='movie',
            name='films_horror',
            field=models.BooleanField(default=False, verbose_name='Жанр - ужасы'),
        ),
        migrations.AddField(
            model_name='movie',
            name='films_romanse',
            field=models.BooleanField(default=False, verbose_name='Жанр - мелодрамма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='mystery',
            field=models.BooleanField(default=False, verbose_name='Жанр - мистика'),
        ),
        migrations.AddField(
            model_name='movie',
            name='science_fiction',
            field=models.BooleanField(default=False, verbose_name='Жанр - фантастика'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cartoons',
            field=models.BooleanField(default=False, help_text='Выберите жанр', verbose_name='Мультфильм'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='films',
            field=models.BooleanField(default=False, help_text='Выберите жанр', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='soap_opera',
            field=models.BooleanField(default=False, help_text='Выберите жанр', verbose_name='Сериал'),
        ),
    ]
