# Generated by Django 4.0.6 on 2022-07-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_anime_movie_films_comedy_movie_films_drama_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='comedy',
            new_name='series_comedy',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='horror',
            new_name='series_horror',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='romanse',
            new_name='series_romance',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='drama',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='soap_opera',
        ),
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.BooleanField(default=False, help_text='Выберите жанр сериала, который добавляете на сайт', verbose_name='Сериал'),
        ),
        migrations.AddField(
            model_name='movie',
            name='series_drama',
            field=models.BooleanField(default=False, verbose_name='Жанр - драма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cartoons',
            field=models.BooleanField(default=False, help_text='Выберите жанр мультфильма, который добавляете на сайт', verbose_name='Мультфильм'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='films',
            field=models.BooleanField(default=False, help_text='Выберите жанр фильма, который добавляете на сайт', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='films_drama',
            field=models.BooleanField(default=False, verbose_name='Жанр - драма'),
        ),
    ]
