# Generated by Django 4.0.6 on 2022-07-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='draft',
        ),
    ]
