# Generated by Django 4.0.6 on 2022-07-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='magnet_link',
            field=models.TextField(default=False, verbose_name='Введите магнет ссылку'),
        ),
    ]
