# Generated by Django 4.0.6 on 2022-07-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_magnet_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='kinopoisk_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=1, verbose_name='Введите год премьеры'),
            preserve_default=False,
        ),
    ]
