# Generated by Django 4.0.6 on 2022-07-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_kinopoisk_id_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='films_romanse',
            new_name='films_romance',
        ),
    ]
