# Generated by Django 4.0.6 on 2022-07-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_rename_films_romanse_movie_films_romance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='movie_shots', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Кадр из фильма',
                'verbose_name_plural': 'Кадры из фильма',
            },
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название фильма'),
        ),
    ]
