# Generated by Django 4.0.6 on 2022-07-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_actor_movie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(upload_to='actors', verbose_name='Изображение'),
        ),
    ]
