# Generated by Django 4.0.6 on 2022-07-10 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_remove_genre_description_remove_genre_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.category', verbose_name='категория'),
        ),
    ]
