# Generated by Django 4.0.6 on 2022-07-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_alter_genre_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='description',
        ),
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.IntegerField(default=0, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='actor',
            name='career',
            field=models.TextField(default=1, max_length=100, verbose_name='Карьера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='genres',
            field=models.TextField(default=1, verbose_name='Жанры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='month',
            field=models.TextField(default=1, verbose_name='Месяц рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='spouse',
            field=models.TextField(default=1, verbose_name='Супруг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='surname',
            field=models.CharField(default=1, max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='total_movies',
            field=models.TextField(default=1, verbose_name='Всего фильмов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Год рождения'),
        ),
    ]
