# Generated by Django 4.0.6 on 2022-07-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_remove_actor_description_actor_birthday_actor_career_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='place',
            field=models.TextField(default=0, verbose_name='Место рождения'),
        ),
    ]
