# Generated by Django 4.0.6 on 2022-07-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_actor_growth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='description',
        ),
        migrations.AddField(
            model_name='director',
            name='birthday',
            field=models.IntegerField(default=0, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='director',
            name='career',
            field=models.TextField(default=1, max_length=100, verbose_name='Карьера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='genres',
            field=models.TextField(default=1, verbose_name='Жанры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='growth',
            field=models.IntegerField(default=0, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='director',
            name='month',
            field=models.TextField(default=1, verbose_name='Месяц рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='place',
            field=models.TextField(default=0, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='director',
            name='spouse',
            field=models.TextField(default=1, verbose_name='Супруг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='surname',
            field=models.CharField(default=1, max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='total_movies',
            field=models.TextField(default=1, verbose_name='Всего фильмов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Год рождения'),
        ),
    ]
