# Generated by Django 4.0.2 on 2022-07-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_remove_director_description_director_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='film_actor', to='movies.Actor', verbose_name='актеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(related_name='category', to='movies.Actor', verbose_name='Категория фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='film_director', to='movies.Director', verbose_name='режисеры'),
        ),
    ]
