# Generated by Django 4.0.2 on 2022-07-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_alter_movie_actors_alter_movie_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default=1, max_length=100, verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
