# Generated by Django 4.0.2 on 2022-07-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_movie_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актер', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Режиссер', 'verbose_name_plural': 'Режиссеры'},
        ),
    ]
