# Generated by Django 4.0.2 on 2022-07-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_alter_actor_options_alter_director_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актера', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Режиссера', 'verbose_name_plural': 'Режиссеры'},
        ),
    ]
