# Generated by Django 4.0.2 on 2022-07-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_alter_actor_options_alter_director_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='career',
            field=models.TextField(max_length=40, verbose_name='Карьера'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
    ]
