# Generated by Django 4.0.2 on 2022-07-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_alter_actor_career_alter_actor_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='total_movies',
            field=models.CharField(max_length=50, verbose_name='Всего фильмов'),
        ),
    ]
